import {parseCsv} from './profile-api.mjs';
const clamp=(v,a=0,b=100)=>Math.max(a,Math.min(b,v));
const num=v=>v===null||v===undefined||v===''?null:(Number.isFinite(+v)?+v:null);
const pulledBool=v=>['1','true','yes','y','pulled'].includes(String(v??'').toLowerCase().trim());
const isoDate=d=>d.toISOString().slice(0,10);
export function dateShift(iso,days){const d=new Date(iso+'T12:00:00Z');d.setUTCDate(d.getUTCDate()+days);return isoDate(d)}
export function estimatePulled(r={}){const direct=r.pulled??r.Pull;if(String(direct??'').trim()!=='')return pulledBool(direct)?1:0;const x=num(r.hc_x),stand=String(r.stand||r.batter_stand||'').trim().toUpperCase();if(x==null||!stand)return'';if(stand==='R')return x<118?1:0;if(stand==='L')return x>132?1:0;return''}
export function statcastOrderKey(r={},idx=0){const d=Date.parse(r.game_date||r.date||r.Date||''),day=Number.isNaN(d)?0:d,ab=num(r.at_bat_number)||0,pitch=num(r.pitch_number)||0,seq=num(r.sequence||r.seq)||idx;return day*1000000+ab*1000+pitch*10+seq/100000}
export function contactEventScore(x={}){const ev=x.ev||0,la=x.la;let s=ev>=105?100:ev>=100?88:ev>=95?74:ev>=90?52:ev>=85?28:8;if(la!=null&&la>=5&&la<=30)s+=8;if(la!=null&&la<-5)s-=10;return clamp(s)}
export function hrEventScore(x={}){const ev=x.ev||0,la=x.la,dist=x.dist||0,pulled=pulledBool(x.pulled);let s=0;if(la!=null&&la>=18&&la<=38){if(ev>=105)s=100;else if(ev>=100)s=88;else if(ev>=95)s=72;else if(ev>=90)s=38}else if(la!=null&&la>=15&&la<=42){if(ev>=105)s=88;else if(ev>=100)s=74;else if(ev>=95)s=58}else if(ev>=105&&la!=null&&la>=10&&la<=45)s=52;if(pulled&&ev>=95&&la!=null&&la>=15&&la<=42)s+=14;if(dist>=390)s+=12;else if(dist>=360)s+=7;else if(dist>=340)s+=3;return clamp(s)}
export function bbeSummary(events=[]){const evs=[...events].sort((a,b)=>(a.sequence??0)-(b.sequence??0)).slice(-15),n=evs.length;if(!n)return null;const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,scoresC=evs.map(contactEventScore),scoresH=evs.map(hrEventScore),newest=evs.slice(-5),prior=evs.slice(0,Math.max(0,n-5)),newestHR=avg(newest.map(hrEventScore)),priorHR=avg(prior.map(hrEventScore)),trendDelta=prior.length?newestHR-priorHR:0,trend=!prior.length?'NEW':trendDelta>=12?'RISING':trendDelta<=-12?'FALLING':'FLAT',count=fn=>evs.filter(fn).length;return{n,contact:avg(scoresC),hrshape:avg(scoresH),hrq:count(x=>hrEventScore(x)>=72),near:count(x=>hrEventScore(x)>=52&&hrEventScore(x)<72),ev95:count(x=>(x.ev||0)>=95),ev100:count(x=>(x.ev||0)>=100),ev105:count(x=>(x.ev||0)>=105),pulledAir:count(x=>pulledBool(x.pulled)&&x.la!=null&&x.la>=15&&(x.ev||0)>=90),hardFlat:count(x=>(x.ev||0)>=95&&x.la!=null&&x.la<15),soft:count(x=>(x.ev||0)<85),trend,trendDelta,newestHR,priorHR,maxEV:Math.max(...evs.map(x=>x.ev||0)),maxDist:Math.max(...evs.map(x=>x.dist||0))}}
export function rowsForPlayer(rows=[],playerId){return rows.filter(r=>+r.batter===+playerId).map((r,idx)=>({ev:num(r.launch_speed),la:num(r.launch_angle),dist:num(r.hit_distance_sc),pulled:estimatePulled(r),sequence:statcastOrderKey(r,idx)})).filter(x=>x.ev!=null||x.la!=null).sort((a,b)=>a.sequence-b.sequence).slice(-15)}
export function buildSavantBbeUrl({ids=[],date}={}){if(!/^20\d\d-\d\d-\d\d$/.test(String(date||'')))throw Error('date required');const clean=[...new Set(ids.map(Number).filter(Number.isInteger))];if(!clean.length)throw Error('ids required');const end=dateShift(date,-1),start=dateShift(end,-20),p=new URLSearchParams({all:'true',hfGT:'R|PO|S|',hfSea:end.slice(0,4)+'|',player_type:'batter',game_date_gt:start,game_date_lt:end,hfFlag:'is..hit..into..play|',min_pitches:'0',min_results:'0',group_by:'name',sort_col:'pitches',player_event_sort:'h_launch_speed',sort_order:'desc',min_abs:'0',type:'details'});for(const id of clean)p.append('batters_lookup[]',String(id));return{url:'https://baseballsavant.mlb.com/statcast_search/csv?'+p.toString(),start,end}}
export function summarizeBbeCsv(csv,{ids=[],date}={}){const rows=parseCsv(csv),{start,end}=buildSavantBbeUrl({ids,date});return ids.map(Number).filter(Number.isInteger).map(player_id=>{const evs=rowsForPlayer(rows,player_id),bbe=bbeSummary(evs);return{player_id,date,start,end,tracked_bbe:evs.length,bbe}})}
