import fs from'node:fs/promises';import vm from'node:vm';import crypto from'node:crypto';import{patchIdentityLoader}from'./patch-identity-loader.mjs';
const O='https://bandalytics-v93-flat-routes.vercel.app',get=async p=>{let r=await fetch(O+p);if(!r.ok)throw Error(p+' '+r.status);return r.text()},sha=s=>crypto.createHash('sha256').update(s).digest('hex');
let m=JSON.parse(await get('/assets-manifest.json')),html=await get('/');
await fs.rm('dist',{recursive:true,force:true});await fs.mkdir('dist/assets',{recursive:true});
let hashes={},assetText={};
for(const[k,f]of Object.entries(m)){let s=await get('/assets/'+f);if(k==='safe-enrich')s=patchIdentityLoader(s);assetText[k]=s;if(f.endsWith('.js'))new vm.Script(s,{filename:f});let out=f;if(k==='safe-enrich'){out='identity-loader.'+sha(s).slice(0,12)+'.js';m[k]=out}hashes[k]=sha(s);await fs.writeFile('dist/assets/'+out,s)}
let h=await fs.readFile('identity-hardening.js','utf8');new vm.Script(h);let hn='identity-hardening.'+sha(h).slice(0,12)+'.js';await fs.writeFile('dist/assets/'+hn,h);
let dr=await fs.readFile('direct-research-ui.js','utf8');new vm.Script(dr);let drn='direct-research-ui.'+sha(dr).slice(0,12)+'.js';await fs.writeFile('dist/assets/'+drn,dr);
let pc=await fs.readFile('direct-parity-compare.js','utf8');new vm.Script(pc);let pcn='direct-parity-compare.'+sha(pc).slice(0,12)+'.js';await fs.writeFile('dist/assets/'+pcn,pc);
let si=await fs.readFile('slate-isolation.js','utf8');new vm.Script(si);let sin='slate-isolation.'+sha(si).slice(0,12)+'.js';await fs.writeFile('dist/assets/'+sin,si);
html=html.replace(/<title>[^<]*<\/title>/,'<title>BANDALYTICS v95 Identity Pitch Fit Safe</title>');
html=html.replace("let b=B[p.player];return b?[p.player,b.n,b.hrq,b.near,b.ev100,b.trend]","let b=window.BANDALYTICS_IDENTITY?.bbeFor?.(p)||B[p.player];return b?[p.player,b.n,b.hrq,b.near,b.ev100,b.trend]");
html=html.replaceAll("new Map(Object.values(P||{}).map(p=>[C(p.player),p]))","new Map(Object.values(P||{}).map(p=>[C(p.player)+'::'+(window.BANDALYTICS_IDENTITY?.teamAlias?.(p.team)||C(p.team||'')),p]))");
html=html.replaceAll("new Map(Object.values(P).map(p=>[C(p.player),p]))","new Map(Object.values(P).map(p=>[C(p.player)+'::'+(window.BANDALYTICS_IDENTITY?.teamAlias?.(p.team)||C(p.team||'')),p]))");
html=html.replaceAll("map.get(C(x.player))","map.get(C(x.player)+'::'+(window.BANDALYTICS_IDENTITY?.teamAlias?.(x.team)||C(x.team||'')))").replaceAll("map.has(C(x.player))","map.has(C(x.player)+'::'+(window.BANDALYTICS_IDENTITY?.teamAlias?.(x.team)||C(x.team||'')))");
html=html.replace("SCHEMA='bandalytics-slate-v72'","SCHEMA='bandalytics-slate-v95-identity-pf'");
html=html.replace("KEEP=['player','team'","KEEP=['player','player_key','player_id','team_key','identity_source','identity_recent_pending','identity_reason','pitchfit_hitter_id','pitchfit_identity_verified','team'");
html=html.replace("if(!mz?.hit||!mz.manifest)return null;const mf=mz.manifest","if(!mz?.hit||!mz.manifest)return null;const mf=mz.manifest;if(mf.schema!==SCHEMA)return null");
html=html.replace("fetch('/api/results?date='+encodeURIComponent(date)","fetch('/api/results-identity?date='+encodeURIComponent(date)");
html=html.replace("['direct','Direct Preview']","['direct','Direct Lab']");
html=html.replaceAll('HR Score v3','Tonight HR Score v37');
// Make historical/current separation obvious on-device so users never confuse the live MLB feed with a loaded historical ZIP.
html=html.replace('<div id="liveFeed" class="panel live-feed">','<div id="historicalModeBanner" class="panel" style="display:none;border-color:rgba(240,180,76,.42);background:linear-gradient(180deg,rgba(44,34,16,.93),rgba(24,19,11,.94))"><div class="eyebrow" style="color:#f0b44c">HISTORICAL SLATE</div><div id="historicalModeText" class="live-feed-text">Current live MLB feed is isolated from this historical ZIP.</div></div><div id="liveFeed" class="panel live-feed">');
html=html.replace("ZIPMODE=classify(ZIPDATE);for(let i=0;i<names.length;i++", "ZIPMODE=classify(ZIPDATE);try{let hb=document.getElementById('historicalModeBanner'),ht=document.getElementById('historicalModeText');if(hb)hb.style.display=ZIPMODE==='HISTORICAL'?'block':'none';if(ht&&ZIPMODE==='HISTORICAL')ht.textContent='Reviewing '+ZIPDATE+' • Current live MLB feed is isolated from this historical ZIP.'}catch{}for(let i=0;i<names.length;i++");
html=html.replace("function clear(){P={};B={};GAMES=[];ZIPDATE=null;ZIPMODE='Waiting';try{CAL=null;CALERR=null}catch{}}", "function clear(){P={};B={};GAMES=[];ZIPDATE=null;ZIPMODE='Waiting';try{let hb=document.getElementById('historicalModeBanner');if(hb)hb.style.display='none'}catch{}try{CAL=null;CALERR=null}catch{}}");
html=html.replace("async function importCsv(file){ZIPDATE=slateDateFromNames([file.name]);ZIPMODE=classify(ZIPDATE);const rs=csv(await file.text());", "async function importCsv(file){ZIPDATE=slateDateFromNames([file.name]);ZIPMODE=classify(ZIPDATE);try{let hb=document.getElementById('historicalModeBanner'),ht=document.getElementById('historicalModeText');if(hb)hb.style.display=ZIPMODE==='HISTORICAL'?'block':'none';if(ht&&ZIPMODE==='HISTORICAL')ht.textContent='Reviewing '+ZIPDATE+' • Current live MLB feed is isolated from this historical CSV.'}catch{}const rs=csv(await file.text());");
// VIG current-slate isolation: validate each CSV row against the official date schedule BEFORE merge().
html=html.replace("catch{}for(let i=0;i<names.length;i++){const n=names[i],rs=csv(await z.files[n].async('text'));if(rs.length)merge(rs,n.split('/').pop());", "catch{}await window.BANDALYTICS_SLATE_ISOLATION?.prepare?.(ZIPDATE,ZIPMODE);for(let i=0;i<names.length;i++){const n=names[i],rawrs=csv(await z.files[n].async('text')),rs=window.BANDALYTICS_SLATE_ISOLATION?.filterRows?.(rawrs)||rawrs;if(rs.length)merge(rs,n.split('/').pop());");
html=html.replace("catch{}const rs=csv(await file.text());if(!rs.length)throw Error('CSV unreadable');merge(rs,file.name);", "catch{}await window.BANDALYTICS_SLATE_ISOLATION?.prepare?.(ZIPDATE,ZIPMODE);const rawrs=csv(await file.text()),rs=window.BANDALYTICS_SLATE_ISOLATION?.filterRows?.(rawrs)||rawrs;if(!rs.length)throw Error('CSV unreadable after slate isolation');merge(rs,file.name);");
html=html.replace("ui.msg.textContent=`IMPORT ✓ ${n} CSV${n===1?'':'s'} • SLATE ${ZIPDATE||'UNKNOWN'} • ${ZIPMODE} • ${Object.keys(P).length} players. Enriching…`;", "{let iso=window.__BANDALYTICS_SLATE_ISOLATION_STATE,cut=iso?.filtered_rows?` • ${iso.filtered_rows} stale VIG rows isolated`:'';ui.msg.textContent=`IMPORT ✓ ${n} CSV${n===1?'':'s'} • SLATE ${ZIPDATE||'UNKNOWN'} • ${ZIPMODE} • ${Object.keys(P).length} players${cut}. Enriching…`;}");
// v95 mixed-date isolation.
html=html.replace("if(m==='games'){let gg=(GAMES||[]).length?GAMES:(window.__LIVE_FEED?.items||[]);return", "if(m==='games'){let sameLive=!ZIPDATE||window.__LIVE_FEED?.date===ZIPDATE,gg=(GAMES||[]).length?GAMES:(sameLive?(window.__LIVE_FEED?.items||[]):[]);if(ZIPDATE&&!sameLive&&!gg.length)return[['Status','Detail'],[['HISTORICAL ZIP ISOLATED','Live MLB feed '+(window.__LIVE_FEED?.date||'today')+' is not mixed into '+ZIPDATE+'. Historical game context comes only from the loaded ZIP / date-scoped enrichment.']]];return");
html=html.replace("if(m==='lineups'){let z=window.__LIVE_FEED?.lineup_players||[],same=window.__LIVE_FEED?.date===ZIPDATE&&Object.keys(P||{}).length>0", "if(m==='lineups'){let sameDate=!ZIPDATE||window.__LIVE_FEED?.date===ZIPDATE,z=sameDate?(window.__LIVE_FEED?.lineup_players||[]):[],same=window.__LIVE_FEED?.date===ZIPDATE&&Object.keys(P||{}).length>0;if(ZIPDATE&&!sameDate)return[['Status','Detail'],[['HISTORICAL ZIP ISOLATED','Current posted lineups '+(window.__LIVE_FEED?.date||'today')+' are intentionally hidden while reviewing '+ZIPDATE+'.']]]");
html=html.replace("['WORKFLOW READY',busy?'Finalizing…':", "['WORKFLOW READY',busy?(ZIPMODE==='HISTORICAL'?'Historical replay…':'Finalizing…'):");
html=html.replace("['TONIGHT HR SCORED',busy?'Finalizing…':", "['TONIGHT HR SCORED',busy?(ZIPMODE==='HISTORICAL'?'Historical replay…':'Finalizing…'):");
// During enrichment, defer heavy derived-board renders.
html=html.replace("function renderMode(m=current){current=m;ui.tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('a',b.dataset.m===m));ui.controls.innerHTML='';ui.title.textContent=(MOD.find(x=>x[0]===m)||[m,m])[1];try{", "function renderMode(m=current){current=m;ui.tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('a',b.dataset.m===m));ui.controls.innerHTML='';ui.title.textContent=(MOD.find(x=>x[0]===m)||[m,m])[1];if(busy&&['calibration','final','snapshot','daily','results'].includes(m)){setPayload(['Status','Detail'],[[ZIPMODE==='HISTORICAL'?'HISTORICAL REPLAY IN PROGRESS':'ENRICHMENT IN PROGRESS','This derived board is deferred until data loading finishes so Safari stays responsive. You can keep browsing the lightweight tabs.']]);return}try{");
html=html.replace("const stats=[['SLATE',a.length?a.length+' ✓':'Waiting'],['MARKET'","const dupCount=window.BANDALYTICS_IDENTITY?.duplicateNameSet?.().size||0;const stats=[['SLATE',a.length?a.length+' ✓':'Waiting'],['IDENTITY',a.length?(a.length+' entities • '+dupCount+' duplicate name'+(dupCount===1?'':'s')):'Waiting'],['MARKET'");
const db=/if\(m==='direct'\)\{[\s\S]*?\};if\(m==='identity'\)/;
const dn=`if(m==='direct'){let z=window.BANDALYTICS_DIRECT_RESEARCH?.getState?.()?.preview?.items||window.__DIRECT_PREVIEW?.items||[];return[['Player','Team','MLB ID','Order','Starter','EV','Hard Hit%','Barrel%','Sweet Spot%','ISO','Savant BBE','Sample','Source','Mode'],z.map(x=>[x.player,x.team,x.player_id??'—',x.lineup,x.opp_pitcher||'TBD',x.ev==null?'—':F(x.ev,1),x.hard_hit==null?'—':F(x.hard_hit,1)+'%',x.barrel==null?'—':F(x.barrel,1)+'%',x.sweet==null?'—':F(x.sweet,1)+'%',x.iso==null?'—':F(x.iso,3),x.bbe_sample??'—',x.sample_grade||'PENDING',x.profile_source||'DIRECT', 'RESEARCH ONLY'])]};if(m==='identity')`;
if(!db.test(html))throw Error('direct tab block not found');html=html.replace(db,dn);
const rb=/if\(m==='results'\)\{[\s\S]*?\};if\(m==='coverage'\)/;
const nr=`if(m==='results'){let z=window.__RESULTS_DATA,rd=window.__RESULTS_DATE,desired=ZIPDATE||ymd();if(!z||rd!==desired)return[['Status','Detail'],[['LOADING','Fetching '+desired+' results…']]];let ID=window.BANDALYTICS_IDENTITY,ik=(n,t)=>ID?.idKey?.(n,t)||('key:'+C(n)+'::'+C(t||'')),pkFor=p=>ID?.identityKey?.(p)||ik(p.player,p.team),lock=window.BANDALYTICS_DAILY?.getPoolLock?.(desired),basis=lock?'LOCKED':(ZIPDATE===desired?'RECOMPUTED':'NO LOADED SLATE'),locked=new Set((lock?.players||[]).map(x=>x.player_key||ik(x.player,x.team))),selected=lock?locked:(ZIPDATE===desired?buildFinalPool():new Set()),all=Object.values(P||{}),byId=new Map(all.filter(p=>p.player_id!=null).map(p=>[+p.player_id,p])),byKey=new Map(all.map(p=>[ik(p.player,p.team),p])),agg=new Map();if(Array.isArray(z.events)){for(const e of z.events){let k=e.batter_id!=null?'id:'+e.batter_id:'key:'+ik(e.player,e.team),q=agg.get(k)||{player:e.player,team:e.team,batter_id:e.batter_id,n:0};q.n++;agg.set(k,q)}}else for(const [name,n] of Object.entries(z.homers||{}))agg.set('name:'+C(name),{player:name,team:null,batter_id:null,n:+n||0});let rows=[];ui.title.textContent='Results — '+desired+' • '+(z.hr_events??[...agg.values()].reduce((a,b)=>a+b.n,0))+' HR events • '+agg.size+' hitters • '+basis.toLowerCase()+' pool basis';for(const e of agg.values()){let p=e.batter_id!=null?byId.get(+e.batter_id):null;if(!p&&e.team)p=byKey.get(ik(e.player,e.team));if(!p){let g=all.filter(x=>C(x.player)===C(e.player));if(g.length===1)p=g[0]}let pk=p?pkFor(p):null,pool=basis==='NO LOADED SLATE'?'—':(pk&&selected.has(pk)?'YES':'NO'),audit=!p?'NOT IN LOADED SLATE':pool==='YES'?(basis==='LOCKED'?'LOCKED POOL HR':'RECOMPUTED POOL HR'):(basis==='LOCKED'?'OUTSIDE LOCKED POOL HR':'OUTSIDE RECOMPUTED POOL HR');rows.push([e.player,e.n,e.team||p?.team||'—',e.batter_id||p?.player_id||'—',pool,basis,p?finalLane(p):'—',p&&tonightScore(p)!=null?F(tonightScore(p),0):'—',p?qualificationLane(p):'—',p?confidenceScore(p)+'%':'—',p?O(p.now):'—',audit])}rows.sort((a,b)=>b[1]-a[1]||String(a[0]).localeCompare(String(b[0])));return[['Player','HR','Team','MLB ID','Pool','Pool Basis','Lane','HR Score','Qualification','Confidence','Odds','Audit'],rows.length?rows:[['NO HR EVENTS','0','—','—','—',basis,'—','—','—','—','—','No recorded HR events']]]};if(m==='coverage')`;
if(!rb.test(html))throw Error('results block not found');html=html.replace(rb,nr);
// Replace the old one-shot Direct Preview bootstrap. Direct Lab now owns identity-first + progressive profile hydration.
const v80=/<script id="v80-direct-preview">[\s\S]*?<\/script>/;
const v80new=`<script id="v80-direct-preview">(function(){function sync(){let R=window.BANDALYTICS_DIRECT_RESEARCH;if(!R){setTimeout(sync,50);return}try{R.refresh();let t=setInterval(()=>{let s=R.getState?.(),p=s?.preview;if(p){window.__DIRECT_PREVIEW=p;let rows=p.items||[],done=rows.filter(x=>x.ev!=null&&x.hard_hit!=null&&x.barrel!=null&&x.iso!=null).length,feed=document.getElementById('liveFeedText'),old=document.getElementById('directProfileStatus');if(feed&&!old){let span=document.createElement('span');span.id='directProfileStatus';feed.appendChild(span);old=span}if(old)old.textContent=' • Direct profiles '+done+'/'+rows.length+(s.hydrating?' hydrating':'');try{if(document.querySelector('#tabs button.a')?.dataset?.m==='direct')window.BANDALYTICS_V56.renderMode('direct')}catch{}}if(s&&!s.loading&&!s.hydrating)clearInterval(t)},350)}catch(e){window.__DIRECT_PREVIEW={ok:false,error:String(e)}}}setTimeout(sync,0)})();window.__BANDALYTICS_V80={directPreview:true,progressiveHydration:true,researchOnly:true,doesNotEnterP:true,doesNotScore:true};<\/script>`;
if(!v80.test(html))throw Error('v80 direct preview bootstrap not found');html=html.replace(v80,v80new);
html=html.replace('</body>',`<script src="/assets/${hn}"></script><script src="/assets/${pcn}"></script><script src="/assets/${drn}"></script><script src="/assets/${sin}"></script><script id="v95-release">window.__BANDALYTICS_V95_RELEASE={exactIdPitchFit:true,directResearchUI:true,directParityComparator:true,vigSlateIsolation:true,modelScoringChanged:false,architecture:'v74'};<\/script></body>`);
let inline=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/g)].map(x=>x[1]).filter(Boolean);for(let i=0;i<inline.length;i++)new vm.Script(inline[i],{filename:'inline-'+i});
if((html.match(/<script[^>]+src="https?:\/\//g)||[]).length)throw Error('external scripts');
for(const marker of ["bandalytics-slate-v95-identity-pf","bbeFor?.(p)","/api/results-identity?date=","MLB ID","Direct Lab","RESEARCH ONLY","duplicate name","progressiveHydration:true"])if(!html.includes(marker))throw Error('html marker '+marker);
for(const marker of ['player_id:+p.player_id','pitchfit_identity_verified=true','Pitch Fit response did not return hitter MLBAM ID','Pitch Fit hitter MLBAM mismatch'])if(!assetText['safe-enrich']?.includes(marker))throw Error('Pitch Fit exact-ID marker missing: '+marker);
let om={...m,'identity-hardening':hn,'direct-parity-compare':pcn,'direct-research-ui':drn,'slate-isolation':sin},integrity={version:'v95',built_at:new Date().toISOString(),base_origin:O,assets:om,sha256:{...hashes,'identity-hardening':sha(h),'direct-research-ui':sha(dr),'direct-parity-compare':sha(pc),'slate-isolation':sha(si)},identity:{entities:'canonical name + canonical team',recent_bbe:'MLBAM player-ID + recovered exact v4 classifier',results:'official MLB batter ID + team',server_schema:'bandalytics-slate-v95-identity-pf',duplicate_true_pitch_fit:'EXACT MLBAM ID REQUIRED; no-ID/mismatch remains RESEARCH'},routing:{core_context_environment_pitchfit:'direct v42',feed_direct:'direct v88',player_bbe:'direct identity loader',results_identity:'local official MLB ID-aware route',direct_profile:'local progressive research-only Savant adapter',market_identity:'local historical MLBAM resolver',research_status:'local fail-closed contract',server_slate:'direct v88'},model_scoring_changed:false,quality_gate:{asset_js_syntax_checked:Object.values(m).filter(x=>x.endsWith('.js')).length+4,inline_js_syntax_checked:inline.length,identity_recent_ui:'PASS',identity_lineup_maps:'PASS',identity_results:'PASS',identity_server_schema:'PASS',duplicate_pitchfit_guard:'PASS',direct_research_ui:'PASS',direct_parity_comparator:'PASS',direct_progressive_hydration:'PASS',vig_slate_isolation:'PASS',external_runtime_scripts:0}};
await fs.writeFile('dist/index.html',html);await fs.copyFile('sim-lab.html','dist/sim.html');await fs.writeFile('dist/assets-manifest.json',JSON.stringify(om));await fs.writeFile('dist/integrity.json',JSON.stringify(integrity,null,2));console.log('v95 BUILD PASS')
