const gates=Object.freeze({
  identity:{status:'PASS',detail:'Exact MLBAM identity resolution is enforced across profile, market and prospective joins. Unresolved market identities fail closed and cannot enter qualifying evidence.'},
  market:{status:'RESEARCH_VALIDATED',detail:'SportsGameOdds MLB batter HR YES is connected in Production. Sep 2 validation matched all 15 MLB slate games and produced exact MLBAM current/open market rows with unresolved identities rejected fail-closed. Immutable intraday context snapshots preserve point-in-time market movement. Research-only; no scoring write access.'},
  sharp_money:{status:'LOCKED',detail:'Legacy sharp-money trigger remains locked at +2.00 implied-probability points; market movement is evaluated separately from hitter qualification.'},
  profile:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'v38 point-in-time profile reconstruction is validated across the preregistered Aug 23-Sep 1 ten-slate window using date-bounded EV, Hard-Hit, Barrel, ISO, Sweet Spot, historical PullAir and Blast semantics. v37 remains frozen; production scoring is unchanged.'},
  bbe:{status:'RESEARCH_VALIDATED_MODIFIER',detail:'Recent BBE latest-contact reconstruction is as-of safe, excludes same-day events, and is captured repeatedly during live pregame windows. Historical results support BBE as a secondary modifier rather than a hard qualification gate.'},
  lineup:{status:'VALIDATED_MODIFIER',detail:'Official MLB posted lineups are frozen in immutable context snapshots. Historical validation supports lineup position only as a small plate-appearance/tie-break modifier; it cannot veto an otherwise qualified power profile.'},
  starter:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'Point-in-time starter HR/9, handedness damage, ISO/SLG allowed and Statcast contact damage are reconstructed with small-IP fail-closed handling. The existing <1.2 HR/9 caution remains a material downgrade rather than an automatic cut.'},
  pitchfit:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'Native Savant Pitch Fit uses exact hitter/pitcher MLBAM IDs and data strictly before the slate date. Across the fixed Aug 23-Sep 1 ten-slate promotion window, 4/6+ISO plus top-quartile PitchFit selected 285 hitters with 47 HR, a 16.49% HR rate, 1.669x population lift, 19.83% HR capture and positive lift on 70% of slates. The lift/stability gates pass, but the preregistered 30% HR-capture gate does not.'},
  bullpen:{status:'SUPPORT_ONLY',detail:'Historical calibration found no reliable standalone HR lift from generic recent bullpen workload. Workload alone cannot raise a candidate grade. Specific reliever availability, handedness and bullpen-quality context remain support/escape inputs only.'},
  environment:{status:'PARITY_BLOCKED',detail:'Venue/weather are frozen in intraday context snapshots, but historical recorded game weather is not yet certified as pregame-equivalent. Environment parity fails closed until coverage/agreement thresholds and deliberate review are satisfied.'},
  park_factor:{status:'PROSPECTIVE_SUPPORT_ACTIVE',detail:'Official Baseball Savant HR park-factor snapshots are captured point-in-time for ALL/L/R batting sides. The daily research board selects only the latest valid park snapshot strictly before each game start using exact venue plus batter handedness. Park factor is support/close-call context only; no hard gate or standalone HR boost.'},
  stack_gascan:{status:'DIAGNOSTIC_ACTIVE',detail:'Same-team stacking remains research-only. The Gas Can study remains pinned to its frozen Aug 26-Sep 1 seven-slate window. Gas Can plus strong profile is a promising research enhancer, but team multi-HR lift was insufficient for stack promotion and generic bullpen workload cannot count as a positive family.'},
  escape_audit:{status:'HISTORICAL_AUDIT_COMPLETE',detail:'The fixed Aug 23-Sep 1 historical Escape Audit is reproducible and manifest-validated: 237 HR total, 47 captured by the quality+top-PitchFit control and 190 outside it. The audit is descriptive only and explicitly cannot change rules, thresholds, scoring, or pool-fill behavior on the same evidence.'},
  escape_watch:{status:'PREREGISTERED_FUTURE_ONLY',detail:'V38_PROSPECTIVE_ESCAPE_WATCH_V1 begins with the Sep 4 slate. It measures quality-profile hitters with top PitchFit versus quality hitters with below-top-quartile or unavailable PitchFit. Sep 2, Sep 3 and all historical slates are barred from this watch; watch groups do not join the core and cannot auto-promote.'},
  automation:{status:'LIVE_RESEARCH_BOARD_ACTIVE',detail:'The canonical v38 live research board runs automatically from profile snapshot -> context/market -> pitch-fit -> Recent BBE -> point-in-time park support -> research hierarchy, with immutable intraday artifacts, the +700 policy scoped separately, and the 20-25 pool target never forced. Vig is optional cross-check only.'},
  prospective:{status:'V5_ACTIVE',detail:'V38_PREGAME_OUTCOME_EVAL_V5 selects the latest valid context, pitch-fit and Recent BBE evidence strictly before each individual game start. Unfinished eligible games prevent finalization. Sep 2 is the first accepted finalized prospective slate; additional independent finalized slates are required.'},
  evidence_manifest:{status:'REQUIRED_FOR_PROMOTION',detail:'Finalized V5 evidence must carry a valid immutable V38_EVIDENCE_MANIFEST_V1 with rule, field, PullAir-threshold, artifact, outcome and selected-pool implementation fingerprints. Historical promotion evidence also requires its fixed ten-slate manifest and reproducible Escape Audit.'},
  v37:{status:'BLOCKED',detail:'Frozen v37 remains unchanged and scoring-ineligible because exact legacy PullAir/Blast parity is not proven.'},
  v38:{status:'MIGRATION_CANDIDATE',detail:'Historical point-in-time reconstruction and the ten-slate promotion window are validated for research. Historical lift/stability/sample gates pass, but HR capture remains below the locked promotion requirement. Additional prospective slates, threshold review, regression and deliberate approval are still required before production scoring cutover.'},
  final_pool:{status:'BLOCKED_PENDING_EVIDENCE',detail:'General final-pool promotion remains fail-closed under V38_FINAL_POOL_PROMOTION_GATE_V1. Current blockers include historical HR capture 19.83% versus required 30%, only one finalized V5 prospective slate versus required three, 15 prospective selected hitters versus 40, 4 prospective HR versus 6, threshold review and deliberate approval. Context, modifier evidence, market reporting, ten historical slates and Escape Audit currently pass. The 20-25 pool size is a target only and is never forced.'},
  tickets:{status:'BLOCKED',detail:'Pool-before-tickets remains enforced; native ticket construction cannot precede final-pool promotion.'}
});
const legacy_lenses=Object.freeze({
  sharp_money:{status:'LOCKED',detail:'Delta implied probability >= +2.00 points remains the recovered locked signal.'},
  steam:{status:'RESEARCH',detail:'Live open/current movement is preserved in immutable pregame context snapshots; exact legacy quote-path semantics remain separate from the new prospective evidence contract.'},
  sweet_spot:{status:'RESEARCH',detail:'Legacy display concepts do not by themselves recreate exact historical membership.'},
  tired_pen:{status:'DEMOTED',detail:'Generic bullpen workload showed no reliable standalone HR lift across historical calibration; workload-only boosting is explicitly disallowed.'},
  gas_can:{status:'DIAGNOSTIC',detail:'Gas Can plus strong profile remains a research contextual enhancer from the frozen seven-slate study. It is not a universal qualification rule or production stack trigger.'},
  double_edge:{status:'RESEARCH',detail:'Cross-layer hitter profile plus matchup/context convergence remains a research concept and cannot bypass locked qualification.'},
  remaining:{status:'RESEARCH',detail:'Barrel Match, Mispriced, Hidden Edge, Sleeper Edge and other legacy tags remain non-scoring until exact semantics and validation are established.'}
});
export default function handler(req,res){
  return res.status(200).json({release:'v95-direct-research-site',production_source:'GITHUB_AUTOMATED_RESEARCH_ACTIVE',direct_mode:'RESEARCH_ONLY',automated_research_flow:true,canonical_research_board_protocol:'V38_LIVE_RESEARCH_BOARD_V1',daily_research_board_protocol:'V38_DAILY_RESEARCH_BOARD_V2',vig_dependency:'OPTIONAL_CROSS_CHECK_ONLY',scoring_enabled:false,model_scoring_changed:false,pool_before_tickets:true,prospective_protocol:'V38_PREGAME_OUTCOME_EVAL_V5',evidence_manifest_protocol:'V38_EVIDENCE_MANIFEST_V1',final_pool_promotion_protocol:'V38_FINAL_POOL_PROMOTION_GATE_V1',prospective_escape_watch_protocol:'V38_PROSPECTIVE_ESCAPE_WATCH_V1',gates,legacy_lenses});
}
