const gates=Object.freeze({
  identity:{status:'PASS',detail:'Exact MLBAM identity resolution is enforced across profile, market and prospective joins. Unresolved market identities fail closed and cannot enter qualifying evidence.'},
  market:{status:'RESEARCH_VALIDATED',detail:'SportsGameOdds MLB batter HR YES is connected in Production. Sep 2 validation matched all 15 MLB slate games and produced exact MLBAM current/open market rows with unresolved identities rejected fail-closed. Immutable intraday context snapshots preserve point-in-time market movement. Research-only; no scoring write access.'},
  sharp_money:{status:'LOCKED',detail:'Legacy sharp-money trigger remains locked at +2.00 implied-probability points; market movement is evaluated separately from hitter qualification.'},
  profile:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'v38 point-in-time profile reconstruction is complete for Aug 26-Sep 1 using date-bounded EV, Hard-Hit, Barrel, ISO, Sweet Spot, historical PullAir and Blast semantics. Seven-slate diagnostics show real HR/non-HR separation. v37 remains frozen; production scoring is unchanged.'},
  bbe:{status:'RESEARCH_VALIDATED_MODIFIER',detail:'Recent BBE latest-contact reconstruction is as-of safe, excludes same-day events, and is captured repeatedly during live pregame windows. Historical results support BBE as a secondary modifier rather than a hard qualification gate.'},
  lineup:{status:'VALIDATED_MODIFIER',detail:'Official MLB posted lineups are frozen in immutable context snapshots. Seven-slate validation supports lineup position only as a small plate-appearance/tie-break modifier; it cannot veto an otherwise qualified power profile.'},
  starter:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'Point-in-time starter HR/9, handedness damage, ISO/SLG allowed and Statcast contact damage are reconstructed with small-IP fail-closed handling. Seven-slate evidence strongly supports the existing <1.2 HR/9 caution as a material downgrade rather than an automatic cut.'},
  pitchfit:{status:'HISTORICAL_RESEARCH_VALIDATED',detail:'Native Savant Pitch Fit uses exact hitter/pitcher MLBAM IDs and data strictly before the slate date. Across Aug 26-Sep 1, 4/6+ISO plus top-quartile pitch-fit was the strongest stable nightly convergence tier: 226 qualified, 49 HR, 21.68% HR rate, 28.65% HR capture and positive lift on all seven slates. Live pitch-fit is captured repeatedly and selected per game strictly before first pitch.'},
  bullpen:{status:'SUPPORT_ONLY',detail:'Seven-slate calibration found no reliable standalone HR lift from generic recent bullpen workload. Workload alone cannot raise a candidate grade. Specific reliever availability, handedness and bullpen-quality context remain valid game-note/escape inputs.'},
  environment:{status:'PARITY_BLOCKED',detail:'Venue/weather are frozen in intraday context snapshots and late-day coverage improved materially, but historical recorded game weather is not yet certified as pregame-equivalent. Environment parity fails closed until coverage/agreement thresholds and deliberate review are satisfied.'},
  park_factor:{status:'PROSPECTIVE_SUPPORT_ACTIVE',detail:'Official Baseball Savant HR park-factor snapshots are captured point-in-time for ALL/L/R batting sides. The daily research board selects only the latest valid park snapshot strictly before each game start using exact venue plus batter handedness. Park factor is support/close-call context only; no hard gate or standalone HR boost.'},
  stack_gascan:{status:'DIAGNOSTIC_ACTIVE',detail:'Same-team stacking remains research-only. Generic bullpen workload cannot count as a positive family. Gas-can starter context is being evaluated across the frozen Aug 26-Sep 1 matrix against qualified 4/6+ISO hitters and same-team multi-HR clustering; thresholds are candidate diagnostics, not production locks.'},
  automation:{status:'LIVE_RESEARCH_BOARD_ACTIVE',detail:'The canonical v38 live research board runs automatically from profile snapshot -> context/market -> pitch-fit -> Recent BBE -> point-in-time park support -> research hierarchy, with immutable intraday artifacts, the +700 policy scoped separately, and the 20-25 pool target never forced. Vig is optional cross-check only.'},
  prospective:{status:'V5_ACTIVE',detail:'V38_PREGAME_OUTCOME_EVAL_V5 selects the latest valid context, pitch-fit and Recent BBE evidence strictly before each individual game start. Unfinished eligible games prevent finalization. Final V5 rows preserve the frozen profile metrics and selected-pool reporting includes captured-price market return.'},
  evidence_manifest:{status:'REQUIRED_FOR_PROMOTION',detail:'Finalized V5 evidence must carry a valid immutable V38_EVIDENCE_MANIFEST_V1 with rule, field, PullAir-threshold, artifact and outcome fingerprints. Promotion readiness deduplicates by manifest evidence identity and rejects malformed or pre-manifest artifacts.'},
  v37:{status:'BLOCKED',detail:'Frozen v37 remains unchanged and scoring-ineligible because exact legacy PullAir/Blast parity is not proven.'},
  v38:{status:'MIGRATION_CANDIDATE',detail:'Historical point-in-time reconstruction and seven-slate convergence are validated for research. Prospective market-linked finalized slates, threshold review, regression and deliberate approval are still required before any production scoring cutover.'},
  final_pool:{status:'BLOCKED_PENDING_PROSPECTIVE',detail:'General final-pool promotion is fail-closed under V38_FINAL_POOL_PROMOTION_GATE_V1. Required evidence includes at least 10 historical slates, selected-pool lift >=1.50x baseline, HR capture >=30%, positive lift on >=70% of slates, at least 3 finalized V5 prospective slates with >=40 selected hitters and >=6 HR, >=90% context coverage, >=80% modifier-evidence coverage, market-band reporting, escape audit, threshold review and deliberate approval. The 20-25 pool size is a target only and is never forced.'},
  tickets:{status:'BLOCKED',detail:'Pool-before-tickets remains enforced; native ticket construction cannot precede final-pool promotion.'}
});
const legacy_lenses=Object.freeze({
  sharp_money:{status:'LOCKED',detail:'Delta implied probability >= +2.00 points remains the recovered locked signal.'},
  steam:{status:'RESEARCH',detail:'Live open/current movement is preserved in immutable pregame context snapshots; exact legacy quote-path semantics remain separate from the new prospective evidence contract.'},
  sweet_spot:{status:'RESEARCH',detail:'Legacy display concepts do not by themselves recreate exact historical membership.'},
  tired_pen:{status:'DEMOTED',detail:'Generic bullpen workload showed no reliable standalone HR lift across the seven-slate calibration window; workload-only boosting is explicitly disallowed.'},
  gas_can:{status:'DIAGNOSTIC',detail:'Starter gas-can context is being tested as an interaction with qualified hitter profiles and team HR clustering. It is not a universal qualification rule or a production stack trigger.'},
  double_edge:{status:'RESEARCH',detail:'Cross-layer hitter profile plus matchup/context convergence remains a research concept and cannot bypass locked qualification.'},
  remaining:{status:'RESEARCH',detail:'Barrel Match, Mispriced, Hidden Edge, Sleeper Edge and other legacy tags remain non-scoring until exact semantics and validation are established.'}
});
export default function handler(req,res){
  return res.status(200).json({release:'v95-direct-research-site',production_source:'GITHUB_AUTOMATED_RESEARCH_ACTIVE',direct_mode:'RESEARCH_ONLY',automated_research_flow:true,canonical_research_board_protocol:'V38_LIVE_RESEARCH_BOARD_V1',daily_research_board_protocol:'V38_DAILY_RESEARCH_BOARD_V2',vig_dependency:'OPTIONAL_CROSS_CHECK_ONLY',scoring_enabled:false,model_scoring_changed:false,pool_before_tickets:true,prospective_protocol:'V38_PREGAME_OUTCOME_EVAL_V5',evidence_manifest_protocol:'V38_EVIDENCE_MANIFEST_V1',final_pool_promotion_protocol:'V38_FINAL_POOL_PROMOTION_GATE_V1',gates,legacy_lenses});
}
